### ISSUE TITLE
friend manager crashes the game

### ISSUE THREAD

**Issue by HausemasterIssue** [Ace8Underscore/CousinWarePriv#2]
idk how but somehow it does

**Comment by HausemasterIssue** [comment]
also would aura attacking urself allow you to take damage from urself via aura?

**Comment by notperry1234567890** [comment]
tragic

**Comment by Ace8Underscore** [comment]
Crashes because of hwid check i put in friend manager(all hwid stuff removed hopefully). Attacking your self will kick from game.
